[package]
name = "openpredict"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[lib]
name = "openpredict"
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
solana-program = "=1.14.13"
spl-associated-token-account = { version = "1.1.3", features = ["no-entrypoint"] }
spl-token = { version = "3.5.0" , features = ["no-entrypoint"] }
quick-protobuf = "0.8.0"
