version: '3'
services:
  search:
    image: getmeili/meilisearch:latest
    environment:
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_ENV=production
      - MEILI_DB_PATH=/data.ms
      - MEILI_LOG_LEVEL=INFO
    volumes:
      - ./data.ms:/data.ms
    ports: 
      - 7700:7700
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./
      dockerfile: ./packages/backend/Dockerfile
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - RPC_URL=${SOLANA_RPC_URL}
      - NODE_ENV=production
      - MAIN_PROGRAM_ID=${MAIN_PROGRAM_ID}
      - USDC_MINT_ADDR=${USDC_MINT_ADDRESS}
      - FEE_PAYER_PRIVKEY=${FEE_PAYER_PRIVKEY}
      - MEILI_HTTP_ADDR=http://search:7700
      - MEILI_API_KEY=${MEILI_MASTER_KEY}
    ports:
      - 3000:3000
    depends_on:
      - search
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./
      dockerfile: ./packages/frontend/Dockerfile
      args:
        - PUBLIC_MAGIC_PUBLISHABLE_API_KEY=${MAGIC_PUBLISHABLE_API_KEY}
        - PUBLIC_MAIN_PROGRAM_ID=${MAIN_PROGRAM_ID}
        - PUBLIC_USDC_MINT_ADDR=${USDC_MINT_ADDRESS}
        - PUBLIC_FEE_PAYER_KEY=${FEE_PAYER_PUBKEY}
        - PUBLIC_SOLANA_RPC_URL=${SOLANA_RPC_URL}
        - PUBLIC_POLYGON_RPC_URL=${POLYGON_RPC_URL}
        - PUBLIC_TRPC_URL=http://localhost:3000
        - PUBLIC_INTERNAL_TRPC_URL=http://backend:3000
        - PUBLIC_WEB3AUTH_ID=${WEB3AUTH_ID}
        - PUBLIC_FAKE_API=false
    environment:
      - INTERNAL_TRPC_URL=http://backend:3000
      - PUBLIC_FAKE_API=false
      - PORT=5173
    ports:
      - 5173:5173  
    depends_on:
      - backend
