export enum Errors {
    LOGGED_OUT = "LOGGED_OUT",
    NO_CONNECTION = "NO_CONNECTION",
    INSUFFICENT_SOL = "INSUFFICENT_SOL",
    INSUFFICENT_USDC = "INSUFFICENT_USDC",
    UNABLE_TO_SWAP = "UNABLE_TO_SWAP",
    NO_WALLET = "NO_WALLET",
    TRANSACTION_FAILED = "TRANSACTION_FAILED",
    CHECK_CONSOLE = "CHECK_CONSOLE"
}